version: "3.9"
services:
    api:
        env_file:
            - api.env
        build: 
            dockerfile: Dockerfile_api
            context: .
        container_name: api
        ports: 
            - "8088:8088"
        links:
            - db
        networks:
            - default
    db:
        build: 
            dockerfile: Dockerfile_db
            context: ./dbinit
        container_name: db
        ports: 
            - "3306:3306"
        networks:
            - default
    frontend:
        env_file:
            - app.env
        build: 
            dockerfile: Dockerfile_app
            context: .
        container_name: frontend
        ports: 
            - "8080:8080"
        links: 
            - api
        networks:
            - default