version: "3.9"
services:
    api:
        env_file:
            - api.env
        build: 
            dockerfile: Dockerfile_api
            context: .
        container_name: car-demo-api
        image: fullaware/car-demo-api
        ports: 
            - "8088:8088"
        networks:
            - default
    frontend:
        env_file:
            - app.env
        build: 
            dockerfile: Dockerfile_app
            context: .
        container_name: car-demo
        image: fullaware/car-demo
        ports: 
            - "8080:8080"
        links: 
            - api
        networks:
            - default
