version: "3.9"
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: I@mR00t
           MYSQL_DATABASE: car_demo
        ports:
            - "3306:3306"
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
    api:
        env_file:
            - api/.env
        build: 
            dockerfile: api/Dockerfile
            context: ./
        container_name: car-demo-api
        image: fullaware/car-demo-api:latest
        ports: 
            - "8088:8088"
        networks:
            - default
    app:
        env_file:
            - app/.env
        build: 
            dockerfile: app/Dockerfile
            context: ./
        container_name: car-demo
        image: fullaware/car-demo:latest
        ports: 
            - "8080:8080"
        links: 
            - api
        networks:
            - default
